# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Info_sotrudniki.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Coos(object):
    def setupUi(self, Coos):
        Coos.setObjectName("Coos")
        Coos.resize(762, 416)
        Coos.setStyleSheet("background-color:rgb(54, 54, 54);")
        self.logs = QtWidgets.QTextEdit(Coos)
        self.logs.setGeometry(QtCore.QRect(20, 90, 721, 251))
        self.logs.setObjectName("logs")
        self.infsotrud = QtWidgets.QLabel(Coos)
        self.infsotrud.setGeometry(QtCore.QRect(300, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.infsotrud.setFont(font)
        self.infsotrud.setStyleSheet("color:rgb(255, 255, 255)")
        self.infsotrud.setObjectName("infsotrud")
        self.back = QtWidgets.QPushButton(Coos)
        self.back.setGeometry(QtCore.QRect(630, 360, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.back.setObjectName("back")

        self.retranslateUi(Coos)
        QtCore.QMetaObject.connectSlotsByName(Coos)

    def retranslateUi(self, Coos):
        _translate = QtCore.QCoreApplication.translate
        Coos.setWindowTitle(_translate("Coos", "Form"))
        self.infsotrud.setText(_translate("Coos", "Сотрудники"))
        self.back.setText(_translate("Coos", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Coos = QtWidgets.QWidget()
    ui = Ui_Coos()
    ui.setupUi(Coos)
    Coos.show()
    sys.exit(app.exec_())
