# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Delit_Sotrudnika.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Delete_Coo(object):
    def setupUi(self, Delete_Coo):
        Delete_Coo.setObjectName("Delete_Coo")
        Delete_Coo.resize(816, 488)
        Delete_Coo.setStyleSheet("background-color:rgb(54, 54, 54);")
        self.infClients = QtWidgets.QLabel(Delete_Coo)
        self.infClients.setGeometry(QtCore.QRect(280, 30, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.infClients.setFont(font)
        self.infClients.setStyleSheet("color:rgb(255, 0, 0)")
        self.infClients.setObjectName("infClients")
        self.FIOsotrud = QtWidgets.QLabel(Delete_Coo)
        self.FIOsotrud.setGeometry(QtCore.QRect(30, 80, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FIOsotrud.setFont(font)
        self.FIOsotrud.setStyleSheet("color:rgb(255, 255, 255)")
        self.FIOsotrud.setObjectName("FIOsotrud")
        self.lineFIO = QtWidgets.QLineEdit(Delete_Coo)
        self.lineFIO.setGeometry(QtCore.QRect(320, 70, 391, 41))
        self.lineFIO.setObjectName("lineFIO")
        self.search = QtWidgets.QPushButton(Delete_Coo)
        self.search.setGeometry(QtCore.QRect(650, 140, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.search.setFont(font)
        self.search.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.search.setObjectName("search")
        self.delete_coo = QtWidgets.QPushButton(Delete_Coo)
        self.delete_coo.setGeometry(QtCore.QRect(690, 420, 111, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.delete_coo.setFont(font)
        self.delete_coo.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 0, 0)")
        self.delete_coo.setObjectName("delete_coo")
        self.logs = QtWidgets.QTextEdit(Delete_Coo)
        self.logs.setGeometry(QtCore.QRect(30, 210, 751, 201))
        self.logs.setObjectName("logs")
        self.back = QtWidgets.QPushButton(Delete_Coo)
        self.back.setGeometry(QtCore.QRect(10, 420, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(0, 255, 0)")
        self.back.setObjectName("back")

        self.retranslateUi(Delete_Coo)
        QtCore.QMetaObject.connectSlotsByName(Delete_Coo)

    def retranslateUi(self, Delete_Coo):
        _translate = QtCore.QCoreApplication.translate
        Delete_Coo.setWindowTitle(_translate("Delete_Coo", "Form"))
        self.infClients.setText(_translate("Delete_Coo", "Удаление Сотрудников"))
        self.FIOsotrud.setText(_translate("Delete_Coo", "Введите ФИО Сотрудника"))
        self.search.setText(_translate("Delete_Coo", "Поиск"))
        self.delete_coo.setText(_translate("Delete_Coo", "Удалить"))
        self.back.setText(_translate("Delete_Coo", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Delete_Coo = QtWidgets.QWidget()
    ui = Ui_Delete_Coo()
    ui.setupUi(Delete_Coo)
    Delete_Coo.show()
    sys.exit(app.exec_())
