# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Delit_Clients.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Delete_Client(object):
    def setupUi(self, Delete_Client):
        Delete_Client.setObjectName("Delete_Client")
        Delete_Client.resize(816, 488)
        Delete_Client.setStyleSheet("background-color:rgb(54, 54, 54);")
        self.infClients = QtWidgets.QLabel(Delete_Client)
        self.infClients.setGeometry(QtCore.QRect(280, 30, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.infClients.setFont(font)
        self.infClients.setStyleSheet("color:rgb(255, 0, 0)")
        self.infClients.setObjectName("infClients")
        self.FIO = QtWidgets.QLabel(Delete_Client)
        self.FIO.setGeometry(QtCore.QRect(30, 80, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FIO.setFont(font)
        self.FIO.setStyleSheet("color:rgb(255, 255, 255)")
        self.FIO.setObjectName("FIO")
        self.fio = QtWidgets.QLineEdit(Delete_Client)
        self.fio.setGeometry(QtCore.QRect(320, 70, 391, 41))
        self.fio.setObjectName("fio")
        self.search = QtWidgets.QPushButton(Delete_Client)
        self.search.setGeometry(QtCore.QRect(650, 140, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.search.setFont(font)
        self.search.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.search.setObjectName("search")
        self.delete_client = QtWidgets.QPushButton(Delete_Client)
        self.delete_client.setGeometry(QtCore.QRect(690, 420, 111, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.delete_client.setFont(font)
        self.delete_client.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 0, 0)")
        self.delete_client.setObjectName("delete_client")
        self.logs = QtWidgets.QTextEdit(Delete_Client)
        self.logs.setGeometry(QtCore.QRect(30, 210, 751, 201))
        self.logs.setObjectName("logs")
        self.exit = QtWidgets.QPushButton(Delete_Client)
        self.exit.setGeometry(QtCore.QRect(10, 420, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(0, 255, 0)")
        self.exit.setObjectName("exit")

        self.retranslateUi(Delete_Client)
        QtCore.QMetaObject.connectSlotsByName(Delete_Client)

    def retranslateUi(self, Delete_Client):
        _translate = QtCore.QCoreApplication.translate
        Delete_Client.setWindowTitle(_translate("Delete_Client", "Form"))
        self.infClients.setText(_translate("Delete_Client", "Удаление Клиентов"))
        self.FIO.setText(_translate("Delete_Client", "Введите ФИО Клиента"))
        self.search.setText(_translate("Delete_Client", "Поиск"))
        self.delete_client.setText(_translate("Delete_Client", "Удалить"))
        self.exit.setText(_translate("Delete_Client", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Delete_Client = QtWidgets.QWidget()
    ui = Ui_Delete_Client()
    ui.setupUi(Delete_Client)
    Delete_Client.show()
    sys.exit(app.exec_())
