# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Enter(object):
    def setupUi(self, Enter):
        Enter.setObjectName("Enter")
        Enter.resize(477, 327)
        Enter.setStyleSheet("background-color:rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(Enter)
        self.label.setGeometry(QtCore.QRect(160, 30, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(170, 0, 255);")
        self.label.setObjectName("label")
        self.Email = QtWidgets.QLabel(Enter)
        self.Email.setGeometry(QtCore.QRect(40, 110, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Email.setFont(font)
        self.Email.setStyleSheet("color:rgb(255, 255, 255)")
        self.Email.setObjectName("Email")
        self.Password = QtWidgets.QLabel(Enter)
        self.Password.setGeometry(QtCore.QRect(40, 160, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Password.setFont(font)
        self.Password.setStyleSheet("color:\n"
"rgb(255, 255, 255)")
        self.Password.setObjectName("Password")
        self.mail = QtWidgets.QLineEdit(Enter)
        self.mail.setGeometry(QtCore.QRect(160, 110, 171, 31))
        self.mail.setObjectName("mail")
        self.enter = QtWidgets.QPushButton(Enter)
        self.enter.setGeometry(QtCore.QRect(320, 210, 141, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.enter.setFont(font)
        self.enter.setAccessibleDescription("")
        self.enter.setAutoFillBackground(False)
        self.enter.setStyleSheet("color:rgb(0, 255, 0)")
        self.enter.setObjectName("enter")
        self.reg = QtWidgets.QPushButton(Enter)
        self.reg.setGeometry(QtCore.QRect(10, 210, 93, 28))
        self.reg.setStyleSheet("color:rgb(0, 255, 255)")
        self.reg.setObjectName("reg")
        self.forgot_pwd = QtWidgets.QPushButton(Enter)
        self.forgot_pwd.setGeometry(QtCore.QRect(360, 110, 93, 28))
        self.forgot_pwd.setStyleSheet("color:rgb(255, 0, 0)")
        self.forgot_pwd.setObjectName("forgot_pwd")
        self.pwd = QtWidgets.QLineEdit(Enter)
        self.pwd.setGeometry(QtCore.QRect(160, 160, 171, 31))
        self.pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd.setObjectName("pwd")
        self.look = QtWidgets.QCheckBox(Enter)
        self.look.setGeometry(QtCore.QRect(360, 160, 91, 31))
        self.look.setObjectName("look")

        self.retranslateUi(Enter)
        QtCore.QMetaObject.connectSlotsByName(Enter)

    def retranslateUi(self, Enter):
        _translate = QtCore.QCoreApplication.translate
        Enter.setWindowTitle(_translate("Enter", "Form"))
        self.label.setText(_translate("Enter", "Вход в Систему"))
        self.Email.setText(_translate("Enter", "Email"))
        self.Password.setText(_translate("Enter", "Password"))
        self.enter.setText(_translate("Enter", "Вход"))
        self.reg.setText(_translate("Enter", "Регистрация"))
        self.forgot_pwd.setText(_translate("Enter", "Забыл пароль"))
        self.look.setText(_translate("Enter", "Показать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Enter = QtWidgets.QWidget()
    ui = Ui_Enter()
    ui.setupUi(Enter)
    Enter.show()
    sys.exit(app.exec_())
