# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(724, 532)
        Menu.setStyleSheet("background-color:rgb(54, 54, 54);")
        self.add_client = QtWidgets.QPushButton(Menu)
        self.add_client.setGeometry(QtCore.QRect(40, 110, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.add_client.setFont(font)
        self.add_client.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.add_client.setObjectName("add_client")
        self.exit = QtWidgets.QPushButton(Menu)
        self.exit.setGeometry(QtCore.QRect(310, 140, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 0, 0)")
        self.exit.setObjectName("exit")
        self.add_coo = QtWidgets.QPushButton(Menu)
        self.add_coo.setGeometry(QtCore.QRect(490, 110, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.add_coo.setFont(font)
        self.add_coo.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.add_coo.setObjectName("add_coo")
        self.oper = QtWidgets.QPushButton(Menu)
        self.oper.setGeometry(QtCore.QRect(280, 280, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.oper.setFont(font)
        self.oper.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(0, 255, 0)")
        self.oper.setObjectName("oper")
        self.check_oper = QtWidgets.QPushButton(Menu)
        self.check_oper.setGeometry(QtCore.QRect(110, 210, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.check_oper.setFont(font)
        self.check_oper.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.check_oper.setObjectName("check_oper")
        self.bills = QtWidgets.QPushButton(Menu)
        self.bills.setGeometry(QtCore.QRect(430, 210, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bills.setFont(font)
        self.bills.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.bills.setObjectName("bills")
        self.label = QtWidgets.QLabel(Menu)
        self.label.setGeometry(QtCore.QRect(290, 40, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 255, 255)")
        self.label.setObjectName("label")
        self.del_client = QtWidgets.QPushButton(Menu)
        self.del_client.setGeometry(QtCore.QRect(30, 450, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.del_client.setFont(font)
        self.del_client.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.del_client.setObjectName("del_client")
        self.del_coo = QtWidgets.QPushButton(Menu)
        self.del_coo.setGeometry(QtCore.QRect(520, 450, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.del_coo.setFont(font)
        self.del_coo.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.del_coo.setObjectName("del_coo")
        self.clients = QtWidgets.QPushButton(Menu)
        self.clients.setGeometry(QtCore.QRect(110, 350, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.clients.setFont(font)
        self.clients.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.clients.setObjectName("clients")
        self.coos = QtWidgets.QPushButton(Menu)
        self.coos.setGeometry(QtCore.QRect(430, 350, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.coos.setFont(font)
        self.coos.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.coos.setObjectName("coos")
        self.exit_2 = QtWidgets.QPushButton(Menu)
        self.exit_2.setGeometry(QtCore.QRect(310, 420, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exit_2.setFont(font)
        self.exit_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 0, 0)")
        self.exit_2.setObjectName("exit_2")

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Form"))
        self.add_client.setText(_translate("Menu", "Добавить Клиентов"))
        self.exit.setText(_translate("Menu", "Выход"))
        self.add_coo.setText(_translate("Menu", "Добавить Сотрудников"))
        self.oper.setText(_translate("Menu", "Провести Операцию"))
        self.check_oper.setText(_translate("Menu", "Мониторинг операций"))
        self.bills.setText(_translate("Menu", "Счета"))
        self.label.setText(_translate("Menu", "Money Foil"))
        self.del_client.setText(_translate("Menu", "Удалить Клиентов"))
        self.del_coo.setText(_translate("Menu", "Удалить Сотрудников"))
        self.clients.setText(_translate("Menu", "Клиенты"))
        self.coos.setText(_translate("Menu", "Сотрудники"))
        self.exit_2.setText(_translate("Menu", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QWidget()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
