# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oper.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Oper(object):
    def setupUi(self, Oper):
        Oper.setObjectName("Oper")
        Oper.resize(868, 470)
        Oper.setStyleSheet("background-color:rgb(54, 54, 54);")
        self.back = QtWidgets.QPushButton(Oper)
        self.back.setGeometry(QtCore.QRect(740, 400, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(171, 171, 171)")
        self.back.setObjectName("back")
        self.Operation = QtWidgets.QLabel(Oper)
        self.Operation.setGeometry(QtCore.QRect(350, 30, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Operation.setFont(font)
        self.Operation.setStyleSheet("color:rgb(255, 255, 255)")
        self.Operation.setObjectName("Operation")
        self.logs = QtWidgets.QTextEdit(Oper)
        self.logs.setGeometry(QtCore.QRect(20, 100, 821, 281))
        self.logs.setObjectName("logs")

        self.retranslateUi(Oper)
        QtCore.QMetaObject.connectSlotsByName(Oper)

    def retranslateUi(self, Oper):
        _translate = QtCore.QCoreApplication.translate
        Oper.setWindowTitle(_translate("Oper", "Form"))
        self.back.setText(_translate("Oper", "Назад"))
        self.Operation.setText(_translate("Oper", "Операции"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Oper = QtWidgets.QWidget()
    ui = Ui_Oper()
    ui.setupUi(Oper)
    Oper.show()
    sys.exit(app.exec_())
