# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Reg(object):
    def setupUi(self, Reg):
        Reg.setObjectName("Reg")
        Reg.resize(506, 369)
        Reg.setStyleSheet("background-color:rgb(54, 54, 54);")
        self.pwd_rep = QtWidgets.QLineEdit(Reg)
        self.pwd_rep.setGeometry(QtCore.QRect(230, 180, 131, 20))
        self.pwd_rep.setText("")
        self.pwd_rep.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_rep.setObjectName("pwd_rep")
        self.login_1 = QtWidgets.QLabel(Reg)
        self.login_1.setGeometry(QtCore.QRect(90, 100, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login_1.setFont(font)
        self.login_1.setStyleSheet("color:rgb(255, 255, 255)")
        self.login_1.setObjectName("login_1")
        self.login = QtWidgets.QLineEdit(Reg)
        self.login.setGeometry(QtCore.QRect(230, 100, 131, 20))
        self.login.setText("")
        self.login.setObjectName("login")
        self.pwd = QtWidgets.QLineEdit(Reg)
        self.pwd.setGeometry(QtCore.QRect(230, 140, 131, 20))
        self.pwd.setText("")
        self.pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd.setObjectName("pwd")
        self.Password = QtWidgets.QLabel(Reg)
        self.Password.setGeometry(QtCore.QRect(90, 140, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password.setFont(font)
        self.Password.setStyleSheet("color:rgb(255, 255, 255)")
        self.Password.setObjectName("Password")
        self.x2Pass = QtWidgets.QLabel(Reg)
        self.x2Pass.setGeometry(QtCore.QRect(50, 180, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x2Pass.setFont(font)
        self.x2Pass.setStyleSheet("color:rgb(255, 255, 255)")
        self.x2Pass.setObjectName("x2Pass")
        self.label_4 = QtWidgets.QLabel(Reg)
        self.label_4.setGeometry(QtCore.QRect(180, 20, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.reg = QtWidgets.QPushButton(Reg)
        self.reg.setGeometry(QtCore.QRect(310, 230, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.reg.setFont(font)
        self.reg.setStyleSheet("color:rgb(0, 255, 0)")
        self.reg.setObjectName("reg")
        self.enter = QtWidgets.QPushButton(Reg)
        self.enter.setGeometry(QtCore.QRect(370, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.enter.setFont(font)
        self.enter.setStyleSheet("color:rgb(0, 255, 255)")
        self.enter.setObjectName("enter")
        self.look_pwd = QtWidgets.QCheckBox(Reg)
        self.look_pwd.setGeometry(QtCore.QRect(390, 140, 81, 20))
        self.look_pwd.setObjectName("look_pwd")
        self.look_pwd_rep = QtWidgets.QCheckBox(Reg)
        self.look_pwd_rep.setGeometry(QtCore.QRect(390, 180, 81, 20))
        self.look_pwd_rep.setObjectName("look_pwd_rep")

        self.retranslateUi(Reg)
        QtCore.QMetaObject.connectSlotsByName(Reg)

    def retranslateUi(self, Reg):
        _translate = QtCore.QCoreApplication.translate
        Reg.setWindowTitle(_translate("Reg", "Form"))
        self.login_1.setText(_translate("Reg", "Логин:"))
        self.Password.setText(_translate("Reg", "Пароль:"))
        self.x2Pass.setText(_translate("Reg", "Повторите пароль: "))
        self.label_4.setText(_translate("Reg", "Регистрация"))
        self.reg.setText(_translate("Reg", "Зарегестрироваться"))
        self.enter.setText(_translate("Reg", "Вход"))
        self.look_pwd.setText(_translate("Reg", "показать"))
        self.look_pwd_rep.setText(_translate("Reg", "показать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Reg = QtWidgets.QWidget()
    ui = Ui_Reg()
    ui.setupUi(Reg)
    Reg.show()
    sys.exit(app.exec_())
